SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.Orders
(
    Id INT IDENTITY(24696, 1) NOT NULL CONSTRAINT PK_dbo_Orders PRIMARY KEY,
    UserId INT NOT NULL CONSTRAINT FK_dbo_Orders_UserId REFERENCES dbo.Users (Id),
    OrderDate DATETIMEOFFSET(7) NOT NULL CONSTRAINT DF_dbo_Orders_OrderDate DEFAULT (SYSDATETIMEOFFSET()),
    CancelDate DATETIMEOFFSET(7) NULL,
    Total DECIMAL(9, 2) NOT NULL CONSTRAINT CK_dbo_Orders_Total CHECK (Total >= 0.00)
)
GO

CREATE INDEX IX_dbo_Orders_UserId_OrderDate ON dbo.Orders (UserId, OrderDate)
GO
