SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.Show
(
    Id INT IDENTITY NOT NULL CONSTRAINT PK_dbo_Show PRIMARY KEY,
    Title NVARCHAR(850) NOT NULL CONSTRAINT CK_dbo_Show_Title CHECK (LEN(Title) > 0),
    MinutesLong SMALLINT NOT NULL CONSTRAINT CK_dbo_Show_MinutesLong CHECK (MinutesLong > 0),
    CONSTRAINT UX_dbo_Show_Title UNIQUE NONCLUSTERED (Title)
)
GO
